runtime: nodejs20

env_variables:
  NODE_ENV: production
  PORT: 8080
  DATABASE_URL: ${DATABASE_URL}
  SESSION_SECRET: ${SESSION_SECRET}

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
- url: /.*
  script: auto
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?node_modules/.*$
- ^(.*/)?\.git/.*$
- ^(.*/)?\.gitignore$
- ^(.*/)?README\.md$
- ^(.*/)?\.local/.*$
- ^(.*/)?client/.*$
- ^(.*/)?server/.*$
- ^(.*/)?shared/.*$
- ^(.*/)?.*\.ts$
- ^(.*/)?.*\.tsx$
- ^(.*/)?vite\.config\.ts$
- ^(.*/)?tailwind\.config\.ts$
- ^(.*/)?postcss\.config\.js$
- ^(.*/)?drizzle\.config\.ts$
- ^(.*/)?tsconfig\.json$